
tmp/linux-5.18.14.tar.xz:
	cd tmp && wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.18.14.tar.xz

tmp/linux-5.18.14/Makefile:
	cd tmp && xzcat linux-5.18.14.tar.xz | tar xfv -

tmp/busybox-1.35.0.tar.bz2:
	cd tmp && wget https://busybox.net/downloads/busybox-1.35.0.tar.bz2

tmp/busybox-1.35.0/Makefile:
	cd tmp && tar -jxvf busybox-1.35.0.tar.bz2
